# Generated by Django 3.2 on 2023-02-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230215_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, verbose_name='Токен'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user_email'),
        ),
    ]
