# Generated by Django 3.2 on 2023-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230219_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default='null', max_length=9999, verbose_name='Код подтверждения'),
        ),
    ]
