# Generated by Django 3.2 on 2023-02-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_titlegenres_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenres',
            options={'verbose_name': 'Произведение, жанр', 'verbose_name_plural': 'Жанры произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория'),
        ),
    ]
